dist: trusty
sudo: false
 
language: python
python:
  - "2.7"
install:
  - pip install flask
  - pip install flask-socketio
  - pip install socketIO_client
script:
  - python ./chatup.py&
  - sleep 3
  - python ./test/test.py